const express = require("express");
const { sanitizeString } = require("../helpers/validators");
const requireJwt = require("../middleware/requireJwt");
const getSupabaseClient = require("../config/supabaseClient");

const router = express.Router();

// ── Helper: decode session_id claim from an already-verified JWT ─────────────
// The signature has already been validated by supabase.auth.getUser inside
// requireJwt, so decoding the payload here is safe.
const extractSessionId = (token) => {
  try {
    const payload = JSON.parse(
      Buffer.from(token.split(".")[1], "base64").toString()
    );
    return payload.session_id ?? null;
  } catch {
    return null;
  }
};

// ── POST /api/auth/password-changed ──────────────────────────────────────────
// Feature 1 — Forgot-password flow (final step).
//
// Called by the client AFTER supabase.auth.updateUser({ password }) succeeds,
// using the temporary recovery session's JWT.
//
// Revokes all active user_devices rows for this user so that every previously-signed-in
// device loses its registered session and must re-authenticate. The client then
// calls supabase.auth.signOut({ scope: 'global' }) and redirects to login.
router.post("/password-changed", requireJwt, async (req, res) => {
  const userId = req.authUser.id;
  const supabase = getSupabaseClient();

  const { error } = await supabase
    .from("user_devices")
    .update({ revoked_at: new Date().toISOString() })
    .eq("user_id", userId)
    .is("revoked_at", null);

  if (error) {
    return res.status(500).json({ error: "Failed to clear device sessions." });
  }
  return res
    .status(200)
    .json({ message: "Password changed. All device sessions cleared." });
});

// ── POST /api/auth/register-device ───────────────────────────────────────────
// Feature 2 — Device registration, called right after signInWithPassword.
// Body: { device_id: string, device_name?: string }
//
// Behaviour:
//   device_id already registered for this user  →  update session_id + last_active_at, 200
//   device count < 3                            →  insert new row, 200
//   device count >= 3                           →  403 + existing device list (device_name, last_active_at)
router.post("/register-device", requireJwt, async (req, res) => {
  let { device_id, device_name } = req.body;
  if (!device_id) {
    return res.status(400).json({ error: "device_id is required." });
  }
  device_id = sanitizeString(device_id, 255);
  device_name = device_name ? sanitizeString(device_name, 100) : null;

  const sessionId = extractSessionId(req.accessToken);
  if (!sessionId) {
    return res.status(400).json({ error: "No session_id found in token." });
  }

  const userId = req.authUser.id;
  const supabase = getSupabaseClient();
  const now = new Date().toISOString();

  // Check if this exact device_id is already registered and active for this user
  const { data: existing, error: lookupError } = await supabase
    .from("user_devices")
    .select("id")
    .eq("user_id", userId)
    .eq("device_id", device_id)
    .is("revoked_at", null)
    .maybeSingle();

  if (lookupError) {
    return res.status(500).json({ error: "Failed to check device." });
  }

  if (existing) {
    // Known device — refresh the session reference and activity timestamp
    const { error: updateError } = await supabase
      .from("user_devices")
      .update({ session_id: sessionId, last_active_at: now })
      .eq("id", existing.id);

    if (updateError) {
      return res.status(500).json({ error: "Failed to update device session." });
    }
    return res.status(200).json({ message: "Device session updated." });
  }

  // New device — check whether there is a free slot
  const { data: deviceList, error: listError } = await supabase
    .from("user_devices")
    .select("device_id, device_name, last_active_at")
    .eq("user_id", userId)
    .is("revoked_at", null);

  if (listError) {
    return res.status(500).json({ error: "Failed to check device count." });
  }

  if (deviceList.length >= 3) {
    return res.status(403).json({
      error: "Maximum device limit reached.",
      devices: deviceList,
    });
  }

  // Insert the new device row (id is generated by the DB default gen_random_uuid())
  const { error: insertError } = await supabase
    .from("user_devices")
    .insert({
      user_id: userId,
      device_id,
      device_name: device_name ?? null,
      session_id: sessionId,
      created_at: now,
      last_active_at: now,
    });

  if (insertError) {
    return res.status(500).json({ error: "Failed to register device." });
  }
  return res.status(200).json({ message: "Device registered." });
});

// ── POST /api/auth/logout-device ─────────────────────────────────────────────
// Feature 2 — Remove a device slot (called from the "too many devices" screen).
// Body: { device_id: string }
//
// Intentionally uses requireJwt (not requireAuth) to skip the device-registered
// check — the caller may not have a registered device yet on this account, which
// is precisely why they need to remove someone else's device.
router.post("/logout-device", requireJwt, async (req, res) => {
  let { device_id } = req.body;
  if (!device_id) {
    return res.status(400).json({ error: "device_id is required." });
  }
  device_id = sanitizeString(device_id, 255);

  const userId = req.authUser.id;
  const supabase = getSupabaseClient();

  const { error } = await supabase
    .from("user_devices")
    .update({ revoked_at: new Date().toISOString() })
    .eq("user_id", userId)
    .eq("device_id", device_id)
    .is("revoked_at", null);

  if (error) {
    return res.status(500).json({ error: "Failed to remove device." });
  }
  return res.status(200).json({ message: "Device removed." });
});

module.exports = router;